apiVersion: v1
data:
    htpasswd: ENC[AES256_GCM,data:sM18ZNCUDKy57po4aKSQbWNPCWNBLS4cIgqlTwQo9KETp64gMDfS+igpn3xxVPi9TLwjxaDK06VEJknvcrsR8chbzxK+bfey6n2yKMlxAlYgsJ2/DfjbkPp6eQ1GOmV1,iv:kCEX+RwZIB6vLqgk31KF7tsD7N0I0KNfWLqPHEZzBjg=,tag:y3XB7sSCLI2iOx60KbZSdw==,type:str]
kind: Secret
metadata:
    name: registry-htpasswd
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146ew5u7ufdeqf80ehh79hmcg93mpyttpzq52erdu769f6wm7xass0amenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWldqSjA0YXdCTmhudnc4
            Q1VrZWNNMG93ME4raVA2R2lubXZWeXlBN3lBCkliOVRNR0tydzUrbFlzODAwYkVH
            UVUvaEYybWtmazJWRm9DYjFQdVJLUlEKLS0tIHBGNVhMQlRTZ3c0UjZNM05ONDU5
            YW1zSzZZMk1scGJqMkR4YzFHQ1lUc1kKGdDdIpJ74U6CQDX4yv9lGkoCxuQZgBH7
            JyPhrXyskRqceU1nuIC++tKRyWaJmPXKLeFMJd6lLLE3bawY2xVXpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T17:02:14Z"
    mac: ENC[AES256_GCM,data:oBvbQWObD9zjaPb6TZl/4XTJ8m8dQ/uZaYc+UIdsqcPOgPesiFmyC7hRenryyOMeU9Cfav+6bTCEkRZtE0TiM857AsoC/TIVVuirdhx5tpbNV/3B9ziybjs61xQ+GmQiQZzkUcI4/PoCMsN5vPO+kFsQR9q7fo+xcknDfBd6L00=,iv:nrHh1D4ns/RPPM25ukaMPL3RxofWO1epcLME1y4x2cQ=,tag:SUYY5PXF5uxWkOB6y6P0wg==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.4
