apiVersion: v1
data:
    htpasswd: ENC[AES256_GCM,data:F8U2HdnK3CQqYlKtmSIBBUjeNtloSzNtvyG9cHoLw9dhnMGOow4B8wJsDoBqJ3fTexMu+5cqd6sn3r620av2qzj9XGaEYnrt1A==,iv:WCq86tbG9FSXZQTI9wg7VoDYtXre2GSzd31o5WeAmvM=,tag:4aU++Dx2vlldWjVDM3827g==,type:str]
kind: Secret
metadata:
    name: registry-htpasswd
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146ew5u7ufdeqf80ehh79hmcg93mpyttpzq52erdu769f6wm7xass0amenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWldqSjA0YXdCTmhudnc4
            Q1VrZWNNMG93ME4raVA2R2lubXZWeXlBN3lBCkliOVRNR0tydzUrbFlzODAwYkVH
            UVUvaEYybWtmazJWRm9DYjFQdVJLUlEKLS0tIHBGNVhMQlRTZ3c0UjZNM05ONDU5
            YW1zSzZZMk1scGJqMkR4YzFHQ1lUc1kKGdDdIpJ74U6CQDX4yv9lGkoCxuQZgBH7
            JyPhrXyskRqceU1nuIC++tKRyWaJmPXKLeFMJd6lLLE3bawY2xVXpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T08:07:45Z"
    mac: ENC[AES256_GCM,data:dn8ko+yt54vXH/Uhe2FYhaKTxntmbpN81E9xD+AbMNtZyPRz5lBzoS8yCnf5697bWQ5QWMg1n/n7p+W/wzAVYIPWAFaCvCzUz2Cc5kZEZbMel1ab+NX64YKsZoYQI+sufCm6+k554T4fA25TAIxDu4oN6+w3ukeXo499Ka+qg7M=,iv:7VsgBhq1edqoG921xI+90BTq+nGE5QT6jdYJuqVQ0to=,tag:uKeW6auuyXbCLEVH5oXhWQ==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.4
