apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-subdir
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nfs-subdir
  project: default
  sources:
  - chart: nfs-subdir-external-provisioner
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    targetRevision: 4.0.18
    helm:
      releaseName: nfs-subdir
      valuesObject:
        nfs:
          server: 192.168.0.246
          path: /var/nfs/shared/Mythallar/k8s

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
