apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: registry
  project: default
  sources:
    - path: k8s/deployments/configs/registry
      repoURL: git@github.com:cniessigma/homelab.git
      targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
