apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  project: default
  sources:
    - path: k8s/deployments/configs/test
      repoURL: git@github.com:cniessigma/homelab.git
      targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true