apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: smi-ost-bot
spec:
  serviceName: smi-ost-bot
  replicas: 1
  selector:
    matchLabels:
      app: smi-ost-bot
  template:
    metadata:
      labels:
        app: smi-ost-bot
    spec:
      containers:
        - name: smi-ost-bot
          image: 192.168.192.100:5000/smi_ost_bot:latest
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: '1'
              memory: 1Gi
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-secrets
                  key: DISCORD_TOKEN
          volumeMounts:
            - name: smi-ost-db
              mountPath: /app/db
  volumeClaimTemplates:
    - metadata:
        name: smi-ost-db
      spec:
        accessModes: [ "ReadWriteMany" ]
        storageClassName: "nfs-client"
        resources:
          requests:
            storage: 1Gi