apiVersion: v1
data:
    DISCORD_TOKEN: ENC[AES256_GCM,data:/IXKpmwvUvwKXD+g5zN4WcCGCdYFnsXr+DjfdotgFkDSD5AdnCJEVGGsikQ6pRzY1ihDO7RfDTEzEleyAD5fnE6wfTgwk22LVFlEs6YwCyk47WtOezwAyaTJk/bvC01zy2P9Fg==,iv:VMBMrVwOrQoQqwrKcqd0F1eQK2/zoSeycNl9mAc2hPg=,tag:TuD86yIQvO88mspTtVyl3g==,type:str]
kind: Secret
metadata:
    name: discord-secrets
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146ew5u7ufdeqf80ehh79hmcg93mpyttpzq52erdu769f6wm7xass0amenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWldqSjA0YXdCTmhudnc4
            Q1VrZWNNMG93ME4raVA2R2lubXZWeXlBN3lBCkliOVRNR0tydzUrbFlzODAwYkVH
            UVUvaEYybWtmazJWRm9DYjFQdVJLUlEKLS0tIHBGNVhMQlRTZ3c0UjZNM05ONDU5
            YW1zSzZZMk1scGJqMkR4YzFHQ1lUc1kKGdDdIpJ74U6CQDX4yv9lGkoCxuQZgBH7
            JyPhrXyskRqceU1nuIC++tKRyWaJmPXKLeFMJd6lLLE3bawY2xVXpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T07:31:14Z"
    mac: ENC[AES256_GCM,data:/4evdarSReJsya7tRt6IqxP477kuBGAvIjZSY9wao/fSs0VPP8e0NzfxAbIX0SVxIYmqAPha6sa8LKFNK6wBMY67OjIFuWIQUoFVZ2BH3jw9+SZ81IFyOyBEE3MeDUAaSUKwvGFD7Hr0uG68LL0LSTcQx5IODn904zjQFzoRoXY=,iv:XI/WrCwiqiF57q5RBD310aUnD0DMYe7vJwxjWLMdYi0=,tag:HqK6r25QzOKG8jWGSLj28A==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.4
