apiVersion: v1
data:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:5zJSDuA+mvjWGtOIr/uof6Uv4aPbPQ02r4cMwNBEeinwymumiz3MwiwO9ag2Z8PGUNJp+ur2qBiECrVaNNirTnyc2HSgkMnE0O2UK/R8VahNj/c5xtncE1ob37A3pV1leBV9NJk4EL0z3Y5QcDcvwAUhrhIhsjA97CBQCnShl5a4JSHCoGX6wtFQPuHugCoNvMC7eiWUkUzCZfVX7dcZ+XlPgyaacVbuv8AMn229NbeX3GBEQxMZQjtGPD8BRODSj8IZjS/xmkx+VBxmk5tPCcI4yuVD7zimk8TefTK3KJUMlfqQyjN58crSMaX6M61JrcOI/JkYY1o=,iv:2ZHmad2hQ0fpy7VsA/x/e1ZNLPSzoWVBNXCWNEs2E50=,tag:rKARDzpAqS1Gey6yTe+h5g==,type:str]
kind: Secret
metadata:
    name: cloudflared-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146ew5u7ufdeqf80ehh79hmcg93mpyttpzq52erdu769f6wm7xass0amenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWldqSjA0YXdCTmhudnc4
            Q1VrZWNNMG93ME4raVA2R2lubXZWeXlBN3lBCkliOVRNR0tydzUrbFlzODAwYkVH
            UVUvaEYybWtmazJWRm9DYjFQdVJLUlEKLS0tIHBGNVhMQlRTZ3c0UjZNM05ONDU5
            YW1zSzZZMk1scGJqMkR4YzFHQ1lUc1kKGdDdIpJ74U6CQDX4yv9lGkoCxuQZgBH7
            JyPhrXyskRqceU1nuIC++tKRyWaJmPXKLeFMJd6lLLE3bawY2xVXpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T01:02:44Z"
    mac: ENC[AES256_GCM,data:c2os6NpaUk7gh/8OQPwb1r5m0N+CrKOr/j0vbg5f8oQPXh3zNcJdD+hl7vHUVYpq8YrTDpe+/OUUapbeI/tJ7yTJnVNyYbfC5vcrizj/LQ880XD9UwonW2VY3rcXAo5adAMbmQv8kpIZ4NKx7HoVE3hkyTYiA5wQ5xV/bYM1WVc=,iv:qsRSJCCe340eEXaUi4jI2uKGTPVKFHvj3s6FBfgHe6Q=,tag:pRLuRhpJ10GyFDwan3O42A==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.4
