apiVersion: v1
data:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:RMm4etK9ahJNXlxqLM/Awo0KoJhfncQIMXRoQKR6sNaM3r+RqrqqjM/eksWRhANHQfCueU7q6Vw=,iv:RlryW1nB2oUOYwanb1VauFAi+5HsN84vSvYzatC3NI0=,tag:k7GllMy+H6DnGcp+kzk9jg==,type:str]
kind: Secret
metadata:
    name: cloudflared-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146ew5u7ufdeqf80ehh79hmcg93mpyttpzq52erdu769f6wm7xass0amenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWldqSjA0YXdCTmhudnc4
            Q1VrZWNNMG93ME4raVA2R2lubXZWeXlBN3lBCkliOVRNR0tydzUrbFlzODAwYkVH
            UVUvaEYybWtmazJWRm9DYjFQdVJLUlEKLS0tIHBGNVhMQlRTZ3c0UjZNM05ONDU5
            YW1zSzZZMk1scGJqMkR4YzFHQ1lUc1kKGdDdIpJ74U6CQDX4yv9lGkoCxuQZgBH7
            JyPhrXyskRqceU1nuIC++tKRyWaJmPXKLeFMJd6lLLE3bawY2xVXpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T00:48:29Z"
    mac: ENC[AES256_GCM,data:hs7THoli8AErrF0PvIuHNodlmrZhhwzhF85teifd+j2R26XfJ1A5cGZD8Rn/J2y5luoOl1Kw+yBtV9yo1CvZeDANtSefb1hI8oOAwhgtSrimRyW6VKIzKX5m01XL0vOkiDtiCIqqWayyeB2i3JGrv9qOri1dTH63OkLq2iQLnk4=,iv:+05SLZ+Y8WHlV9zT6knlUjPmbE3S0mi13PWvflr1vLs=,tag:dksbpp+82XsoFue0MG5ZWg==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.4
